# Generated by Django 4.0.5 on 2022-07-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=40)),
                ('problem_level', models.IntegerField()),
                ('problem_desc', models.TextField()),
            ],
        ),
    ]
