# Generated by Django 4.0.5 on 2022-07-05 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(max_length=30)),
                ('submitted_at', models.DateTimeField()),
                ('submittedcode', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinejudge.problem')),
            ],
        ),
    ]
